[package]
name = "permutate"
version = "0.1.0"
authors = ["Mifour <dufour.thomas@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutate = "0.3.2"
